---
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart awx-web
  ansible.builtin.service:
    name: awx-web
    state: restarted

- name: restart awx-task
  ansible.builtin.service:
    name: awx-task
    state: restarted

- name: restart awx-receptor
  ansible.builtin.service:
    name: awx-receptor
    state: restarted

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted