---
- name: Fetch DB password from Secrets Manager
  amazon.aws.aws_secret:
    name: "{{ awx_db_secret_name }}"
    region: "{{ aws_region | default('us-east-1') }}"
  register: db_secret
  when: awx_db_secret_name is defined

- name: Set DB password from secret
  ansible.builtin.set_fact:
    awx_db_password: "{{ db_secret.secret }}"
  when: awx_db_secret_name is defined

- name: Fetch admin password from Secrets Manager
  amazon.aws.aws_secret:
    name: "{{ awx_admin_secret_name }}"
    region: "{{ aws_region | default('us-east-1') }}"
  register: admin_secret
  when: awx_admin_secret_name is defined

- name: Set admin password from secret
  ansible.builtin.set_fact:
    awx_admin_password: "{{ admin_secret.secret }}"
  when: awx_admin_secret_name is defined