---
- name: Install AWX on RHEL 9 controller
  hosts: awx_controllers
  become: true
  gather_facts: true

  vars:
    aws_region: "us-east-1"
    awx_db_host: "awx-postgres.cejy0ioq489t.us-east-1.rds.amazonaws.com"
    awx_db_secret_name: "awx/db-password"
    awx_admin_secret_name: "awx/admin-password"

  roles:
    - role: platform.automation.os_baseline
      tags: [os_baseline]

    - role: platform.automation.awx_install
      tags: [awx_install]